In [ ]:
#groupby()
#agg()

In [1]:
import pandas as pd
import numpy as np

exam = pd.read_csv("data/exam.csv")
exam.groupby("nclass") \
    .agg(mean_math = ("math", "mean"))

        mean_math
nclass
1           46.25
2           61.25
3           45.00
4           56.75
5           78.00

In [2]:
exam.groupby("nclass", as_index = False) \
.agg(mean_math = ("math", "mean"))

   nclass  mean_math
0       1      46.25
1       2      61.25
2       3      45.00
3       4      56.75
4       5      78.00

In [ ]:
exam.groupby("nclass")
.agg(mean_math= ("math", "mean"),
    sum_math=)

In [3]:
mpg = pd.read_csv("data/mpg.csv")

mpg.groupby(["manufacturer", "drv"])\
.agg(mean_cty = ("cty", "mean"))

                   mean_cty
manufacturer drv
audi         4    16.818182
             f    18.857143
chevrolet    4    12.500000
             f    18.800000
             r    14.100000
dodge        4    12.000000
             f    15.818182
ford         4    13.307692
             r    14.750000
honda        f    24.444444
hyundai      f    18.642857
jeep         4    13.500000
land rover   4    11.500000
lincoln      r    11.333333
mercury      4    13.250000
nissan       4    13.750000
             f    20.000000
pontiac      f    17.000000
subaru       4    19.285714
toyota       4    14.933333
             f    21.368421
volkswagen   f    20.925926

In [4]:
mpg["drv"].value_counts()

drv
f    106
4    103
r     25
Name: count, dtype: int64

In [7]:
mpg.query('category == "suv"') \
.assign(total = mpg["hwy"] + mpg["cty"]) \
.groupby("manufacturer") \
.agg(mean_tot = ("total", "mean")) \
.sort_values("mean_tot", ascending = False).head()

               mean_tot
manufacturer
subaru        43.833333
toyota        32.625000
nissan        31.750000
mercury       31.250000
jeep          31.125000

In [11]:
mpg.groupby("category") \
.agg(mean_cty = ("cty", "mean")) \
.sort_values("mean_cty", ascending= False)

             mean_cty
category
subcompact  20.371429
compact     20.127660
midsize     18.756098
minivan     15.818182
2seater     15.400000
suv         13.500000
pickup      13.000000

In [12]:
mpg.groupby("category") \
.agg(mean_hwy = ("hwy", "mean")) \
.sort_values("mean_hwy", ascending= False).head(3)

             mean_hwy
category
compact     28.297872
subcompact  28.142857
midsize     27.292683

In [ ]:
mpg.query('category == "compact"') \
    .groupby("manufacturer") \
.agg(n = ) \
.sort_values("mean_hwy", ascending= False).head(3)

In [13]:
name = pd.DataFrame({"nclass" : [1, 2, 3, 4,5 ],
                    "teacher" : ["김", "구", "름", "비", "숑"]})
name

   nclass teacher
0       1       김
1       2       구
2       3       름
3       4       비
4       5       숑

In [14]:
exam_new = pd.merge(exam, name, how = "left", on = "nclass")
exam_new

    id  nclass  math  english   science teacher
0    1       1    50       98  10000000       김
1    2       1    60       97        60       김
2    3       1    45       86        78       김
3    4       1    30       98        58       김
4    5       2    25       80        65       구
5    6       2    50       89        98       구
6    7       2    80       90        45       구
7    8       2    90       78        25       구
8    9       3    20       98        15       름
9   10       3    50       98        45       름
10  11       3    65       65        65       름
11  12       3    45       85        32       름
12  13       4    46       98        65       비
13  14       4    48       87        12       비
14  15       4    75       56        78       비
15  16       4    58       98        65       비
16  17       5    65       68        98       숑
17  18       5    80       78        90       숑
18  19       5    89       68        87       숑
19  20       5    78       83        58       숑

In [19]:
group_a = pd.DataFrame({"groomi": [1,2,3,4,5],
                       "cute": [22,33,44,55,66]})
group_b = pd.DataFrame({"groomi": [1,2,2,6,5],
                       "cute": [22,33,"김구름이",34343,66]})
group_all = pd.concat([group_a, group_b], ignore_index = True)
group_all

   groomi   cute
0       1     22
1       2     33
2       3     44
3       4     55
4       5     66
5       1     22
6       2     33
7       2   김구름이
8       6  34343
9       5     66

In [20]:
fuel = pd.DataFrame({"fl": ["p", "r", "d", "e","c"],
                    "price_fl": [20000, 2000.22, 333333.3333, 222424225.242424, 242424.54]})
mpg = pd.merge(mpg, fuel, how = "left", on = "fl")
mpg

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category,price_fl
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact,20000.0
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact,20000.0
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact,20000.0
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact,20000.0
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact,20000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize,20000.0
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize,20000.0
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize,20000.0
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize,20000.0
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize,20000.0

In [24]:
import pandas as pd
import numpy as np

midwest = pd.read_csv("data/midwest.csv")

midwest["percentage"] = (midwest["poptotal"] - midwest["popadults"]) / midwest["poptotal"] * 100
midwest

,PID,county,state,area,poptotal,popdensity,popwhite,popblack,popamerindian,popasian,...,percprof,poppovertyknown,percpovertyknown,percbelowpoverty,percchildbelowpovert,percadultpoverty,percelderlypoverty,inmetro,category,percentage
0,561,ADAMS,IL,0.052,66090,1270.961540,63917,1702,98,249,...,4.355859,63628,96.274777,13.151443,18.011717,11.009776,12.443812,0,AAR,34.486307
1,562,ALEXANDER,IL,0.014,10626,759.000000,7054,3496,19,48,...,2.870315,10529,99.087145,32.244278,45.826514,27.385647,25.228976,0,LHR,36.721250
2,563,BOND,IL,0.022,14991,681.409091,14477,429,35,16,...,4.488572,14235,94.956974,12.068844,14.036061,10.852090,12.697410,0,AAR,35.501301
3,564,BOONE,IL,0.017,30806,1812.117650,29344,127,46,150,...,4.197800,30337,98.477569,7.209019,11.179536,5.536013,6.217047,1,ALU,37.440758
4,565,BROWN,IL,0.018,5836,324.222222,5264,547,14,5,...,3.367680,4815,82.505140,13.520249,13.022889,11.143211,19.200000,0,AAR,31.819740
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,3048,WAUKESHA,WI,0.034,304715,8962.205880,298313,1096,672,2699,...,7.667090,299802,98.387674,3.121060,3.785820,2.590061,4.085479,1,HLU,35.731093
433,3049,WAUPACA,WI,0.045,46104,1024.533330,45695,22,125,92,...,3.138596,44412,96.330036,8.488697,10.071411,6.953799,10.338641,0,AAR,34.693302
434,3050,WAUSHARA,WI,0.037,19385,523.918919,19094,29,70,43,...,2.620907,19163,98.854785,13.786985,20.050708,11.695784,11.804558,0,AAR,31.307712
435,3051,WINNEBAGO,WI,0.035,140320,4009.142860,136822,697,685,1728,...,5.659847,133950,95.460376,8.804031,10.592031,8.660587,6.661094,1,HAU,36.602052
436,3052,WOOD,WI,0.048,73605,1533.437500,72157,90,481,722,...,4.583725,72685,98.750085,8.525831,11.162997,7.375656,7.882918,0,AAR,36.422797

In [25]:
top5 = midwest.sort_values('percentage', ascending = False).head(5)
top5[['county', 'percentage']]

        county  percentage
230   ISABELLA   51.501172
404  MENOMINEE   50.591260
281     ATHENS   49.320727
247    MECOSTA   49.059183
154     MONROE   47.358182

In [27]:
midwest['grade'] = pd.cut(
    midwest['percentage'],
    bins = [0, 10, 20, 30, 100],
    labels = ['1등급', '2등급', '3등급', '4등급']
)
midwest['grade'].value_counts().sort_index()

grade
1등급      0
2등급      0
3등급      9
4등급    428
Name: count, dtype: int64

In [28]:
midwest['percentage'] = (
    midwest['popasian'] / midwest['poptotal'] * 100
)

bottom10 = midwest.sort_values(
    'percentage',
    ascending=True
).head(10)
bottom10[['state', 'county', 'percentage']]

    state     county  percentage
404    WI  MENOMINEE    0.000000
105    IN     BENTON    0.010592
109    IN    CARROLL    0.015950
358    OH     VINTON    0.027032
390    WI       IRON    0.032504
85     IL      SCOTT    0.053154
112    IN       CLAY    0.060716
261    MI     OSCODA    0.063759
340    OH      PERRY    0.066546
73     IL      PIATT    0.070749